# Dependencies
markdown:         kramdown
highlighter:      rouge
remote_theme:     fongandrew/hydeout

# Setup
title:            The painting of the voice
tagline:          'A Jekyll theme'
description:      'The Notes'
url:              https://rayworks.github.io


author:
  name:           'Sean Zhou'
  url:            https://github.com/rayworks

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
hydeout:
  repo:  https://github.com/rayworks
